apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parentapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gigawhat/k8s-sandbox.git
    targetRevision: HEAD
    path: argocd/parentapps/k8s-sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
