apiVersion: v1
kind: Secret
metadata:
  name: k8s-sandbox
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/gigawhat/k8s-sandbox.git
