apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: app1-
namespace: app1

commonLabels:
  app: app1

resources:
  - namespace.yaml
  - ../base

images:
  - name: podinfo
    newName: podinfo/podinfo
    newTag: 6.2.0
